### ISSUE TITLE
"Add Created Date" not working

### ISSUE THREAD

**Issue by ghost** [benrhughes/todotxt.net#141]
Since the last update, my new tasks do not get their created date added. No error is shown.

**Comment by paullemmens** [comment]
For me this is not (yet) solved; or only partially. It seems to be related to having entered a second date for a task, for instance, for those of using threshold tasks (although these are not functional in todotxt.net).

Try the following tasks (my comment after the pound sign):
test due:today # works for me
test due:today t:2015-09-18 # fails, no created date
test due:tod # works, faulty due date intended
test due:tod t:2015-09-18 # fail
test due:tody t:1234 # works
test due:today 2015-09-18 # fails

So it appears that todotxt.net gets confused when it sees more dates in the tasks than it is expecting / able to parse. Somehow that results in the created date not being added at the front.

HTH
