### ISSUE TITLE
Epic: Backlog Prioritizing Mode

### ISSUE THREAD

**Issue by chipbite** [benrhughes/todotxt.net#163]
If you are a little agile influenced, you may prioritize your todo file in top to bottom order.

The first task is the most important, and so on.
A text editor works nicely to do this. You can select multiple rows and move them around.

Naturally, the order of the taskrows when working like this is key, the order manifests the result of your latest review of your todolist - what tasks you plan to do next or soon.

To support this mode/or approach todotxt.net needs to be able to 
- add tasks at a specific row (#164)
- move a taskrow and move several taskrows up or down (#125 and partly #134)

To have some sort of reference, I suggest to call this "Backlog Prioritizing Mode" or just backlog mode for short.

**Comment by ThomasHjortsberg** [comment]
This is the only reason why I still use Sublime Text for todo.txt. I cannot live without being able to reorder lines.
