### ISSUE TITLE
Add pageup and pagedown as navigation keys

### ISSUE THREAD

**Issue by chipbite** [benrhughes/todotxt.net#167]
I can navigate using letters and arrow keys.
Since arrowkeys and pageup/down keys are a standard way to navigate lists and rows (in editors) in many windows applications I would expect pageup/down to work as well, hopping down one page at a time (dependent on windowsize / how much of the list is visble)

Please consider adding this navigation - since there is no way to effectively navigate the larger list via the keyboard today, it seems.

**Comment by chipbite** [comment]
Hey guys, this one seems fixed to me. Navigation with todays release seems flawless, smooth.

Moving to close as fixed. @mjdescy @benrhughes Again, great release today. The app gives you a solid feeling.

**Comment by mjdescy** [comment]
@chipbite Thanks for the kind words! "A solid feeling" is definitely one of the things I was going for in my patches.
