### ISSUE TITLE
Check main application window is within screen boundaries when starting

### ISSUE THREAD

**Issue by andrewgreig** [benrhughes/todotxt.net#175]
I often connect my laptop to an external monitor, and have todotxt.net on the second screen.

If I run with just one monitor todotxt.net opens off-screen with no easy way to move it back.

Manually changing the value of WindowLeft in user.config is a workaround, but ideally the application would check and adjust this value automatically.

**Comment by benrhughes** [comment]
I believe this was fixed a while back. Closing.
