### ISSUE TITLE
New feature: Highlighting for contexts, projects and other stuff

### ISSUE THREAD

**Issue by lexmosolov** [benrhughes/todotxt.net#208]
Like QTodoTxt
http://3.bp.blogspot.com/-ciP77lBW9JE/TfU3zWEcZ5I/AAAAAAAABJ8/NAqqWaKW8D0/s1600/QTodoTxt-windows.png

**Comment by benrhughes** [comment]
Thanks for the suggestions. todotxt.net is in maintenance mode and no new features are likely to be added.
