### ISSUE TITLE
Do not remove empty lines

### ISSUE THREAD

**Issue by chipbite** [benrhughes/todotxt.net#218]
todotxt.net can use the file sort order and respects it.

As per earlier discussions, todotxt does not / should not process the empty lines, but leave them as is (#162 ignore blank lines and #126 Blank lines can be completed).

However, when I save, empty lines are removed.

1. Create todo.txt file with contents like:
```
Mail +mom with new house address after @move

Schedule +painter-mike for fence after @move to new house

```
1. Open in todotxt.net (add a task) and save it. 
1. Open todo.txt in other editor 

Expected: Task added, other pre-existing content unchanged.
Actual: Task added, empty lines have been removed.

**Comment by robertvanbregt** [comment]
The original todo.sh removes text from lines but leaves the lines as is by default. If todotxt.net respects the original behaviour it should at least provide a setting.
