### ISSUE TITLE
Add sort options to filters

### ISSUE THREAD

**Issue by cjrobe** [benrhughes/todotxt.net#227]
I love the quick filter options but wish that a filter could also change the sort mode. When I'm viewing all my tasks, I like to have it sorted by context. My first filter is my @work filter and I would like the option so that it will change the sort by project when that filter is enabled.

Maybe add some sort of syntax in the filter box? So "@work sort:7" would filter by @work and sort by project (control+7 is the kb shortcut for sort by project).

**Comment by muteboy** [comment]
Definitely seconded. I came here to ask this. I just donated as well :)

**Comment by flight16** [comment]
Thirded.  This would be very handy.

**Comment by muteboy** [comment]
Seems like a combination of filter and sort called a "view" would be useful.

**Comment by benrhughes** [comment]
Thanks for the suggestions. todotxt.net is in maintenance mode and no new features are likely to be added.
