### ISSUE TITLE
Color coding

### ISSUE THREAD

**Issue by StudioHo** [benrhughes/todotxt.net#230]
Hi! Congratulations for great app!
The only feature I think missing is really color coding.

For example, isn't

(A) @Email [+Boss]() about bug in  [+A105KL]()

quicker and easier to read than

`(A) @Email +Boss about bug in  +A105KL`

**Comment by jucor** [comment]
This seems to have been done in PR #368  -- @benrhughes  , does the maintenance mode allow for merging PRs please?
