### ISSUE TITLE
Command line parameters for settings and todo.txt files

### ISSUE THREAD

**Issue by benrhughes** [benrhughes/todotxt.net#235]
eg todotxt.exe /ini=settings.ini /data=todo.txt

**Comment by shulist** [comment]
Ben,
I just saw this entry and would like to encourage you to get it into the next release. Even if it only a filename parameter as  that would be a great improvement. I open four todotxt files at the same time on one of my screens and leave them on their own desktop. It would be great to do this automatically at boot time.

**Comment by benrhughes** [comment]
todotxt.net is in maintenance mode and no new features are likely to be added.
