### ISSUE TITLE
Ctrl+Alt+direction and screen orientation

### ISSUE THREAD

**Issue by philuk1971** [benrhughes/todotxt.net#242]
On my Windows 7 desktop PC and laptop Ctrl+Alt+Direction key changes the orientation of the screen and have in versions of Windows since I can remember.

I leave this partly as a suggestion to change the hotkeys chosen for increasing/decreasing due dates and partly to inform anyone with the same issue that it is possible to disable the screen orientation hotkeys. Ctrl+Alt+F12 got me to the options to to so.

Cheers

Phil

**Comment by aaronalfano** [comment]
@philuk1971 Thanks for the tip!

**Comment by muteboy** [comment]
I had this problem as well. I don't need the screen rotation, so I disable the Intel tool hotkeys.
