### ISSUE TITLE
Performance Problem with Sort with Grouping Enabled

### ISSUE THREAD

**Issue by mjdescy** [benrhughes/todotxt.net#261]
By accident today, I loaded my done.txt file, which is 200KB (about 2,600 lines), in Todotxt.net and found that the app froze for a while (with a "(Not Responding)" message in the title bar) while the app sorts the task list by any of the sort options that emit group headers (e.g., project, context, priority, due date, etc.). Sorting speeds up considerably when "Allow grouping of tasks" is turned off.

In my normal use of this app, I never hit this performance problem, due to regular archiving of tasks.

**Comment by mpcjanssen** [comment]
I just did a test in Simpletask with 4000 tasks and grouping is pretty much instant. You might want to check the adapter code for an idea of how it's implemented.
