### ISSUE TITLE
Preserve priority when completing task

### ISSUE THREAD

**Issue by flusi100** [benrhughes/todotxt.net#265]
In a completed task, the priority can be preserved between completion date an creation date. Currently priority is beeing deleted when a task is marked as completed.

Accidentialy hitting the "x" can be undone by hitting "x" again, but priority is lost.

For me it is also of interest to archive the priority attached to completed tasks.

**Comment by benrhughes** [comment]
Hi,
For better or worse, this is part of the todo.txt spec (
https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format) so
todotxt.net won't be changing this behavior.

Thanks for the suggestion though.

Cheers,

Ben

**Comment by flusi100** [comment]
Hi Ben,

thank you for the quick reply. In my opinion it is not defined, whether priority has to be discarded or not on completion. But I'm sure this is a question of interpretation or interpolation in between the few simple rules defining todo.txt. Both variants are compliant.

Of course, as mentioned in the linked tutorial, using value:key (eg pri:a ...) would be a possiblity to preserve information on completion. But when using todotxt.net some functionality would be missing (shortcut for priority setting).

As you mentioned right, it was just a suggestion. And even if it is not going to be implemented, todotxt.net will stay my favorite tool managing my todos.

Regards,
Martin

**Comment by benrhughes** [comment]
Hi Martin,
Sorry, you're right : the spec is ambiguous. I mis-remembered. What I was
thinking of was a fairly lengthy discussion on the mailing list about
changing the behaviour of the commandline app to maintain priority. The
decision was to retain the current behaviour and the spec was updated with
the workaround.

Glad you like the app :-)

Cheers,

Ben

**Comment by flight16** [comment]
I would also like to see priority preserved.  When reviewing what I completed for the day/week it would be nice to easily see "These were all of the high-value tasks".

**Comment by flight16** [comment]
@benrhughes Would you accept a pull request with an optional feature to write priority to tag "pri" upon completion?

**Comment by benrhughes** [comment]
Yep, that sounds good.

**Comment by sstebann** [comment]
Hello, so how we can preserve priority? is there a workaround? or it will be implemented soon, sorry but I get confused.

Thank you,
Esteban

**Comment by fleapower** [comment]
Portable version which retains priority at https://github.com/fleapower/todotxt.net/.  It is based on [jdckr's fork](https://github.com/jdckr/todotxt.net).
