### ISSUE TITLE
Prepend Text

### ISSUE THREAD

**Issue by mjdescy** [benrhughes/todotxt.net#271]
Feature description: Prepend text, entered in an alert window, to selected tasks.

Behavior: Prepending text to a task with a priority or a creation date will insert text after the priority or creation date. Otherwise, it will insert text at the start of the task.

Use case: Typically this would be added to add creation dates, projects, or contexts to existing tasks.

**Comment by robertvanbregt** [comment]
+1

very much required for prepending creation date. Anything else could be appended.

If implemented then it would be nice if the prepend actually respects both completed tasks (x mark and date) and already added creation date

1. If creation date present then prepend after creation date but before anything else
2. if task completed than prepend after date completed but before anything else
3. if both completed and creation date present than prepend after creation date but before anything else

**Comment by mjdescy** [comment]
I worked on this feature a few months ago. There are bugs in Todotxt.net's Todo Lib that need to be fixed before prepend text will work properly. My proposal is swapping out the library with a new on I coded https://github.com/mjdescy/TodoTxtWin. This would be a major upgrade to the "engine" of the app, which is one reason I held off on the update so far.
