### ISSUE TITLE
Remember list position when deleting a task

### ISSUE THREAD

**Issue by benrhughes** [benrhughes/todotxt.net#280]
When you delete a task, the focus goes back to the first task in the list. It would be better if it went to the preceding task.

**Comment by mjdescy** [comment]
The change would have to take into account multiple selection, too. There can be multiple tasks that are deleted in a single operation. The new selection should be the task immediately prior to the first task deleted, or the beginning of the list if the first task is deleted. I think it may be trickier to code this than it sounds.

**Comment by chipbite** [comment]
+1 on this one! It is annoying when reviewing and deleting old stuff and obsoleted tasks, for instance.

**Comment by lorentrogers** [comment]
+1 for me too!

**Comment by EdgarAllenPoe** [comment]
+1

**Comment by benrhughes** [comment]
Thanks for the suggestions. todotxt.net is in maintenance mode and no new features are likely to be added.
