### ISSUE TITLE
Focus on next task in list when completing a task in sorted view

### ISSUE THREAD

**Issue by chipbite** [benrhughes/todotxt.net#282]
## Repro:
- Start and load tasklist, preferably large (more than one screen)
- Sort on prio: have a few A and B tasks
- complete an (A) task

**Expected:** Task is marked as completed and dissappears (is moved to bottom seems to happen, which is good). Focus/Position of screen is kept where I am so I can continue working in current position, marking next task complete, etc.

**Actual:** Task is moved to bottom, focus moves to bottom as well and I must move back to top of list manually.

**Proposal:** Focus on next or previous task in list? Not sure, but it would work from user POV, I think.

**Comment by mjdescy** [comment]
In practice, this is harder to do than you'd think it would be. I'm starting to want this feature, too, though.

**Comment by benrhughes** [comment]
Thanks for the suggestions. todotxt.net is in maintenance mode and no new features are likely to be added.
