### ISSUE TITLE
Filter done tasks

### ISSUE THREAD

**Issue by metbril** [benrhughes/todotxt.net#284]
Feature request:

**hide done tasks or show only done tasks**

Use cases: 
- hide done tasks without/before archiving
- show only done tasks before archiving

like due, use something like `@done` or `-@done` for negative search

**Comment by charlesroper** [comment]
Hi, I'm interested in this too. I tried filtering using `-x` but that excludes every task with an x in it, not matter where the x occurs (in the word "next" for example).

**Comment by benrhughes** [comment]
todotxt.net is in maintenance mode and no new features are likely to be added.
