### ISSUE TITLE
Intellisense phrases do not reflect current task list

### ISSUE THREAD

**Issue by dlip** [benrhughes/todotxt.net#287]
You added intellisense to the filters window, how about adding it to the edit todo field also?

**Comment by benrhughes** [comment]
I'm not sure I understand: intellisense has been in the edit field since
v0.8.2 (mid 2011)

Cheers,

Ben

**Comment by dlip** [comment]
Ah, i was starting a new file and it seems you need to reload the program to cache the intellisense, is that correct behavior?

**Comment by benrhughes** [comment]
Hmm, that shouldn't happen. It should look at your task list on the fly to
work out what the current projects, contexts etc are. We may have broken it
at some stage.

**Comment by dlip** [comment]
One way to reproduce is if you create new a new todo.txt in a different folder all your intellisense will be still cached from the last file. If you exit and come back to your new file that is empty and start adding things, none of your intellisense works until you restart or press f5.

**Comment by benrhughes** [comment]
Thanks for the detail - I can reproduce it. I guess it slipped through
because most people are working with a fairly stable set of contexts and
projects.

**Comment by dlip** [comment]
I've tested at home, and I can still reproduce the old intellisense cache when creating a new file, but in normal use the cache updated as expected. Both version 3.2.0.0.
I reinstalled on my work pc and for normal use it's working properly so you can probably lower the priority of the ticket now.
Not sure what it was, maybe old files from a previous install?...
Thanks for your help
