### ISSUE TITLE
Add set priority to documentation

### ISSUE THREAD

**Issue by dlip** [benrhughes/todotxt.net#288]
It would be good if I could press a key followed by a letter to directly set the priority. For example 's c' would set the priority to c,  this would avoid losing my home row position and having to move to the arrow keys.

**Comment by benrhughes** [comment]
Hi Dane,
I don't mind that idea at all. My only concern would be that we'd be using
up 26 key combos for a single feature, and we'd be sure to clash with some
existing combos. Would it work for you if we made Alt-j and Alt-k work the
same way as Alt-Up and Alt-Down?

Cheers,

Ben

**Comment by mjdescy** [comment]
Shortcut key `I` already does this, via a pop up.

**Comment by dlip** [comment]
You are right! Awesome!

Can you please add it to the about page then?

**Comment by benrhughes** [comment]
I forgot about 'i' - looks like it's not on our help screen :-)
