### ISSUE TITLE
Blank child windows on Windows 10

### ISSUE THREAD

**Issue by windracer** [benrhughes/todotxt.net#290]
Hello, thank you for the useful and simple app!

I use todotxt.net on Windows 10 upgraded from Windows 8.1 (64 bit). Child windows like Options or About are blank most of the times I lauch them. If I move mouse over the controls, some of them appear (I guess because they handle *WM_MOUSEHOVER* message. Sometimes windows are OK (~10-20% of launches). I have fixed the same issue in my own project (*please read below*).

**Please see the screenshots:**

Options is blank:
![1 options-blank](https://cloud.githubusercontent.com/assets/9411121/9266811/4325335c-4270-11e5-884a-0a26b99d0039.png)

Options after I move mouse over the window:
![2 options-mousemove](https://cloud.githubusercontent.com/assets/9411121/9266812/4736a5c0-4270-11e5-9f5e-e55742d01e37.png)

About is blank:
![3 about-blank](https://cloud.githubusercontent.com/assets/9411121/9266815/49665764-4270-11e5-91e5-b36d1840d43d.png)

About is OK:
![4 about-ok](https://cloud.githubusercontent.com/assets/9411121/9266816/4baedabe-4270-11e5-9b1d-ea8b01c27424.png)

## Here's how I fixed the same issue in my project. 

Please note that this is a temporary solution and I was not able to find any other solution in the Internet. If you find any other solution, please let me know.

First, simple repainting (via InvalidateVisual()) does not solve the problem. 

I decided to handle the ContentRendered event and hide and then show back all the controls. *mainGrid* is a name of the topmos Grid on my window. Here's the code:

XAML:
```
    <Window x:Class="...."
        .........
        ContentRendered="Window_ContentRendered" 
        ...... >
```
CS:
```c#
        private void Window_ContentRendered(object sender, EventArgs e)
        {
            InvalidateVisual(); // Just in case
            var childCount = VisualTreeHelper.GetChildrenCount(mainGrid);
            for (int i = 0; i < childCount; ++i)
            {
                var child = VisualTreeHelper.GetChild(mainGrid, i) as UIElement;

                if (child != null)
                {
                    child.Visibility = Visibility.Hidden;
                    child.Visibility = Visibility.Visible;
                }
            }
        }
```
Hope the solution will help or you will find another solution which will be more appropriate.

**Comment by benrhughes** [comment]
Thanks. I'm not seeing the issue here on Win10: everything seems to render as expected. I'll hold off putting any time into this until we hear from other people: perhaps it's a hardware specific issue?

**Comment by windracer** [comment]
Thanks for the quick reply! Actually, I don't know. Maybe it is something very special to my computer. 

I have a fresh insallation of Windows 10 on Hyper-V and cannot reproduce the issue on that machine - it appears only on my primary developer computer upgraded from Win8.1 and only for WPF applications. Previously on the primary computer I used Windows 8.1 upgraded from Windows 8 (and had no blank screen problem).

**Comment by benrhughes** [comment]
I've just upgraded my work machine from 7 to 10, and I haven't seen any UI rendering issues in either todotxt or our (rather larger :)) WPF app, so fingers crossed it's some weirdness in your setup.

I'll close this for now, but re-open if we get more reports.

Cheers,

Ben
