### ISSUE TITLE
Flexible styling using CSS in printed version? (todotxt.net)

### ISSUE THREAD

**Issue by muteboy** [benrhughes/todotxt.net#291]
I'm really liking, and have donated to, todotxt.net.
I like to print a filtered todo list to work with at home, stick on the fridge, hand to others, add to in pen etc. The print preview is good, but I would like more flexibility in the formatting. I viewed the source of the HTML print preview, and edited the CSS to make it more paper-friendly; added cell borders, a couple of other tweaks.
2 questions/requests:
1. Would it be possible to have the generated HTML refer to an external CSS file? Then a user could set one up that they like, without too much fiddling each time. Perhaps a new Option to either use internal or external CSS.
2. Could we get another couple of cells added in each row? Perhaps one at the start and one at the end of each row? Give them a CSS id, then they could be either ignored or formatted in some way by the external CSS, perhaps as a checkbox on the printed page.

**Comment by mjdescy** [comment]
@muteboy That's kind of an interesting idea. I imagine an intermediate XML format that can be transformed to xhtml.

Printing isn't a feature I ever use, though. It's good to know that someone does. I don't really understand why the print method does what it does with the task text, though. Wouldn't it be better to print out the text as is, and add some styling and color to things like projects and contexts?

**Comment by benrhughes** [comment]
As a bit of history, the current print process came in as a pull request
from someone with a specific use case. This was back in the early days, and
I didn't spend enough time vetting PRs to make sure that they were
generically useful. I've never used the print stuff myself, so it's
certainly possible that it has some irregularities.

**Comment by muteboy** [comment]
If I were a coder, I would take a stab at it. The key advantage of this tool is its simplicity. I wouldn't want to bloat it up, but consider this:
The Print Preview already generates HTML, so perhaps add a *File > Export to HTML* function to do it directly. Then tweak the code that creates the HTML to include internal CSS, but refer to an external CSS file that the user could create. Just put the link to the external file **after** the internal definitions, so that the external one would override the internal.
I really like this tool, and appreciate the effort that goes into it. I wish I could contribute more. I could create an ideal HTML - would that be useful?

**Comment by benrhughes** [comment]
That's a good approach, IMO.
