### ISSUE TITLE
Summary side-window

### ISSUE THREAD

**Issue by sssimon** [benrhughes/todotxt.net#292]
It would be a great feature to have an (optional) side window which shows your projects, contexts, etc. much like the part on the left in this screenshot from QTodoTxt:
![image](https://cloud.githubusercontent.com/assets/1589895/10361337/d4e557c4-6da7-11e5-9080-6ca82c203906.png)
Clicking on any element in this list could open the associated filter, for example, clicking on "Projects" would show all tasks with a project whereas selecting a project name would filter tasks within that project.

This would be really useful because:

- it gives you an instant overview of your tasks (e.g., do I have any tasks in the @errands context)
- it allows you to quickly filter by various task properties and focus on a given context or project (then, within that focus, if you're adding new tasks they're already tagged with that context/project because of the filter integration).

**Comment by muteboy** [comment]
I really like the clean keyboard-driven look of todotxt.net. But I think it would be useful to have a status bar showing what the current filter and count was. Also a reminder of the keyboard commands!

**Comment by mjdescy** [comment]
I would love a sidebar that is easy to show/hide with a keyboard shortcut, too. My idea would be to have a sidebar that let you set the filter via checking off which priorities, projects, or contexts you want to see. It's just lower on my priority list than a lot of other things.

**Comment by benrhughes** [comment]
The idea of todotxt.net was always to be a minimal, keyboard-driven layer
over the todo.txt file - mostly because that's what I wanted. I still think
the minimalist approach should be retained, particularly with regards to
the main UI (options is already over-complicated, and getting worse, IMO).

So I'm not opposed to a sidebar as such, but it's bordering on being a step
too far, IMO. It would depend a lot on the implementation.

**Comment by muteboy** [comment]
As a user, I agree with Ben. A status bar with info (and maybe keyboard reminders?) at the bottom would be great, but a sidebar would be too much.

**Comment by sssimon** [comment]
I agree with Ben's minimalist philosophy. I would advocate the side window only as a keyboard shortcut-enabled toggle.

**Comment by benrhughes** [comment]
This is (I think) covered by #279 which @sckaushal has just implemented.

**Comment by sssimon** [comment]
The status bar is an excellent idea though it provides stats only for the current filter. Also, I understand your reasons for keeping the UI simple, Ben. Therefore, I propose a different addition: the summary window. You press a hotkey (M?) and a new window opens up (much like the help window) and it provides a summary of your projects and contexts and the number of open tasks in each. 

Feel free to trash this idea, I love todotxt.net no matter what :)
