### ISSUE TITLE
Keyboard command help screen too tall for laptop screen.

### ISSUE THREAD

**Issue by muteboy** [benrhughes/todotxt.net#293]
The keyboard command help screen is too tall for my laptop screen. It overlaps at the top and bottom, so I have to Win+Left to shift it to my attached monitor to resize it. Could it be rearranged to be more landscape-shaped?

**Comment by muteboy** [comment]
There's no scroll bar either. It could be small, with a scroll bar.

**Comment by lehasb** [comment]
I also have this issue (Windows 7, 1440x900 resolution) with the window appearing taller than is visible on my screen. The window also appears with a vertical scrollbar, but never has a horizontal scrollbar, even if the window is resized so not all the text is visible horizontally.

**Comment by wierzba3** [comment]
I've submitted a pull request fixing this issue. It appears that the textbox that contains the help text was auto-filling it's height. Since there was so much text, it filled it past the height of most screen resolutions
