### ISSUE TITLE
Hotkey already in use

### ISSUE THREAD

**Issue by szepeviktor** [benrhughes/todotxt.net#294]
Error: `Hotkey already in use`
In Windows 10 <kbd>WIN</kbd> + <kbd>T</kbd> is for displaying a list of wifi networks.

**Comment by szepeviktor** [comment]
Please consider introducing an option for the hotkey.

**Comment by szepeviktor** [comment]
```
<kbd>T</kbd>
```
for displaying nice keys in markdown

**Comment by benrhughes** [comment]
Hi Viktor,
todotxt.net doesn't use win-t, as far as I'm aware. It does use win-alt-t -
are you saying that using win-alt-t gives you the error?

Cheers,

Ben

**Comment by szepeviktor** [comment]
Sorry. Here it is with <kdb>Alt</kbd>
http://windows.microsoft.com/en-us/windows-10/keyboard-shortcuts-for-game-bar

**Comment by benrhughes** [comment]
Great, thanks.

**Comment by synick** [comment]
I just changed the hotkey in the code: MainWindow.xaml.cs

**Comment by fretep** [comment]
Suggestions on how this should be fixed?
1. Option to disable the hotkey (easy, I could implement assuming a pull request would be accepted)
2. Static alternative hotkey (easy, I could implement assuming a pull request would be accepted)
3. Ability to select a hotkey (bit more work, I'm probably not interested in doing a pull request for this)
4. Something else?

Assuming an alternative hotkey, what should it be?

Viable, but somewhat disappointing workaround is to disable minimize to tray as the hotkey is only registered when this option is set.

synick, are you planning on doing a pull request? What alternative key did you choose?

**Comment by synick** [comment]
Submitted pull request.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by TommiG2** [comment]
I am using V3.3.0.0 portable version and if option "minimise to system tray" is on, at every start of the app the message "Hotkey already in use" appears.
Therefore I cleared the system tray option and everything is fine for me.
BTW: Win10 1903 german.
@benrhughes Thank you for this useful app.
