### ISSUE TITLE
Always-on-top setting

### ISSUE THREAD

**Issue by flight16** [benrhughes/todotxt.net#297]
It would be handy if I could set todotxt.net to be always be on top so I don't forget what I'm working on when I'm interrupted.  I enjoy doing this with OneNote and other todolists I've used.

**Comment by mjdescy** [comment]
I wonder if something like this would work, with an option to turn it on or off:

~~~c#
Window parent = Window.GetWindow(this);
parent.Topmost = true;
~~~

**Comment by tbone2k-git** [comment]
+1

Thanks! o)

**Comment by benrhughes** [comment]
Thanks for the suggestions. todotxt.net is in maintenance mode and no new features are likely to be added.
