### ISSUE TITLE
How do I filter by priority?

### ISSUE THREAD

**Issue by flight16** [benrhughes/todotxt.net#298]
How can I create a filter for all tasks that have a priority B-Z?  I couldn't find any documentation under "Help".  Maybe documentation for priority syntax could be added there?

**Comment by benrhughes** [comment]
Easiest way, though it's a bit of a hack,  would be to filter on "!(A)".
Downside is that it will also pick up tasks with no priority.

**Comment by flight16** [comment]
"!(B)" doesn't return any tasks, even though I have tasks with priority A-C.  "(B)" returns tasks with priority B.

Is there a way to return tasks with priority A-C?

**Comment by muteboy** [comment]
There's another Feature Request about enabling "OR" statements in filters. That would enable this.
