### ISSUE TITLE
Due dates in YYYY-MM-D or YYYY-M-DD format aren't recognized

### ISSUE THREAD

**Issue by flight16** [benrhughes/todotxt.net#299]
I think todotxt.net would be friendlier if it accepted non-zero-padded dates.

I have a task "Do stuff due:2015-11-3".  When I sort by due date it is grouped under n/a.  I realize this is technically expected because it doesn't conform to YYYY-MM-DD, but I'd argue it's not always natural to include leading zeros when entering dates.

**Comment by benrhughes** [comment]
I can see where you're coming from, but my memory of the spec is that the
date format is explicit. The issue with allowing non-standard date formats
would be that you could create todo.txt files that other todo.txt clients
could not read.

**Comment by flight16** [comment]
I see.  Perhaps there could be an option for TodoTxt.Net to pre-process dates, converting "2015-1-3" into "2015-01-03" when user hits enter?

Different but related, it would be nice to have similar behavior with relative dates: due:fri gets converted into 2015-10-30, due:5d gets converted into 2015-11-03, etc.
