### ISSUE TITLE
more options for due date

### ISSUE THREAD

**Issue by ChrisPurves** [benrhughes/todotxt.net#301]
Currently, there are a few user friendly options for setting the due date:

due:tomorrow
due:friday

These are then converted to a date and saved.

What about:

due:*n*day[s]
due:*n*week[s]
due:*n*month[s]

where *n* is a numeral

Maybe I'm dumb or lazy, but I often find myself, wanting to set something two weeks ahead, then having to look up what day it is today, and on from there.

**Comment by mjdescy** [comment]
Do you know about the `s` (set due date) and `p` (postpone) keyboard shortcuts on the task list? You can set due dates for one or more selected tasks, and use either the keyboard or a calendar picker to choose the date. I know those options are not in the text edit box, but they are pretty handy.

**Comment by ChrisPurves** [comment]
Was not aware about 's' shortcut.  Definitely handy.  I would still prefer a more convenient text option, but I won't complain if this feature request is not adopted.
