### ISSUE TITLE
Bug: "Exit" on tray-icon not working

### ISSUE THREAD

**Issue by bttrx** [benrhughes/todotxt.net#302]
Right-clicking the tray-icon and choosing "Exit" does nothing on my two Windows 7 laptops.

**Comment by bttrx** [comment]
+1

**Comment by benrhughes** [comment]
I can reproduce. Not sure when that broke!

**Comment by bttrx** [comment]
Can somebody fix it, please? :-)

Robert

Am 29.08.2016 1:51 nachm. schrieb "Ben Hughes" <notifications@github.com>:

**Comment by madman2021** [comment]
Please note this is fixed.
