### ISSUE TITLE
Use active filter for new to-dos

### ISSUE THREAD

**Issue by bttrx** [benrhughes/todotxt.net#303]
This would be of great help to avoid typing, e.g., "@Home" or "@Work" over and over again, because I usually have the correct filter applied before creating new to-dos.

Use hotkey "N" for the current behaviour and new hotkey "Alt+N" to create a new task prefilled with the current filter.
Make this reversible via the options screen.

**Comment by lehasb** [comment]
In the version I'm running (3.2.0) the current behavior is for the new task hotkey "N" to create a task with the current filter automatically appended. It can't be turned off via the options, but this seems to do most of what you are requesting already. Are you running an up-to-date version?

**Comment by bttrx** [comment]
I'm also running 3.2.0, but have never used "N". I usually click into the top textbox to enter new tasks. I'll test it for the next days.

**Comment by bttrx** [comment]
I'm fine with.
