### ISSUE TITLE
can't execute updates

### ISSUE THREAD

**Issue by gutmannmartin** [benrhughes/todotxt.net#310]
hey! i just got into todotxt recently and use it heavily already. after some use the update of a task can not be saved to the list anymoreby hitting enter. reinstalling worked a couple of times but not anymore. installing 3.1 helped for a while but came up with the same issue. also restarting the computer doesn't help. has anyone got an idea why this is happening? 

cheers!

**Comment by benrhughes** [comment]
I haven't seen or hear of this behaviour before. When you say that it's 'not saved', what is happening?

Also, if you go to File -> Options and enable debug logging, does anything show up in the log (Help -> View Error Log)?

**Comment by benrhughes** [comment]
Haven't heard back. Closing for now - will re-open if more info comes to light.

**Comment by gutmannmartin** [comment]
hello ben,

sorry for the late reply. the issue is still there. 
some more info: i run on windows 10, 64bit; for now the only way of updating and creating new tasks is to write directly into the text file, which works perfectly. 
changing priorities within todotxt works also fine. 
so the only thing is, if i create a new task or update a task i can't safe it.

in the error log on e repeated message is "file change observer enabled"

cheers
