### ISSUE TITLE
Auto-completion lists content does not update upon opening a different todo file

### ISSUE THREAD

**Issue by aprilia1k** [benrhughes/todotxt.net#314]
**ISSUE** - auto-completion dropdown for _+Project_ does not get updated when a different todo file is opened.  _Problem applies to @Context auto-complete as well_.

    todotxt.net has a handy auto-complete feature for Project and Context assignment.  
    Entering '+' activates the Project list, entering '@' activates the Context list.

**Reproduction:**

-     Have two different todo files that contain some different project names (and/or context entries)
-     Start program and observe that the auto-complete dropdown works correctly for the initial todo file.
-     Select _File..Open_ and open a different todo file (e.g. foo2.todo.txt)
-     Start entering a new task, and type '+' to bring up the Project auto-complete list.  Observe that the entries in the list are from the originally loaded todo file (foo1.todo.txt).

Observation/Analysis:
Apparently the **Project** and **Context** _auto-completion_ lists get initialized at program start, and never get updated, regardless of any subsequent todo files that are opened.

**_Workaround_** - somewhat obviously, by exiting after the desired todo file is opened, the auto-completion entries for projects and contexts will appear correctly after starting the app again.  

Prioritization:
Assuming that most users only use a single todo file, this issue is probably not very urgent.  Logging it for posterity.

**Comment by benrhughes** [comment]
Duplicates #287
