### ISSUE TITLE
Feature Request : View completed tasks

### ISSUE THREAD

**Issue by sarathkcm** [benrhughes/todotxt.net#315]
Hi,

Nice work on the application. I have tried so many applications for keeping TODO lists; and I liked todotxt.net because of its feature richness with simplicity. I have been a user for almost an year now and I am using it at work. 

This is a feature request, not an issue.

Having to provide updates everyday morning to the team, I find it a bit difficult to search archived tasks text file and find out the task I marked complete the previous day.

It would be nice to have a View Completed Tasks option (In New Tab may be) so that Tasks which are completed can be easily be found. This can be filtered based on date, and can have an option to display tasks from archived Files too( text with strike does not look good, so I prefer to archive them tasks as and when completed.)

Can this be done?

Also, it can be nice to have a task display like below if it is a todo:
  
   ☐ This task should be completed

And when completed it can be shown as below (preferably green tick mark )

   ✔ This task is a completed task

**Comment by sarathkcm** [comment]
I was talking about showing completed tasks like this in the list.

![image](https://cloud.githubusercontent.com/assets/14143311/17251225/ac1f63f8-559f-11e6-817b-0cb523524bd3.png)

**Comment by benrhughes** [comment]
Hi,
It does this out of the box, unless I'm misunderstanding your question:

[image: pasted1]


Cheers,

Ben
