### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by MannyDo** [benrhughes/todotxt.net#316]
Hi, 
Thanks for your development of this great tool, I 'm a user of version 3.2.0, I noticed that there is an new version reminder at the right conner of menu bar, but when I check the release page, it's still 3.2.0, did I miss something?

**Comment by benrhughes** [comment]
Hi,
I'm not sure what's happening there - it seems to be functioning correctly for me. A new release should come out in the next couple of weeks. I'll close this for now, but if you still see the behavior after you've installed the next release please let me now and I'll re-open and investigate.

Cheers,

Ben
