### ISSUE TITLE
Unable to add new tasks

### ISSUE THREAD

**Issue by hoosteen** [benrhughes/todotxt.net#319]
After pressing N to add a new task and filling in the text field, pressing 'enter' results in nothing. Task not added to list, text remains in text box for editing.

**Comment by mjdescy** [comment]
@hoosteen,

Make sure you don't have a filter applied. Press 0 (zero) when focus is in the task list, or use the Filter menu, to remove the filter.

Also, have you opened your todo.txt file yet? 

Note that "Move focus to task list after creating new task" is an option in the options. See File > Options in the menu or press F10 to see them.
