### ISSUE TITLE
Paste multiple tasks

### ISSUE THREAD

**Issue by benrhughes** [benrhughes/todotxt.net#320]
As a counterpart to the new(ish) copy multiple tasks functionality, it would be good to be able to paste multiple tasks. I propose it would work like this:

- select newline delimited tasks from some other text editor and copy to clipboard
- select task list (*not* the input box) in todotxt
- Ctrl-V
- the pasted text can either be:
 - directly appended to the todo.txt file, then re-load the file
 - split on newline and parsed into Task objects, which are then added via the usual new task process

This idea was suggested by Peter Gorrill via email.

**Comment by mjdescy** [comment]
This was implemented a while ago. See Issue #220.

**Comment by benrhughes** [comment]
LOL, I had a feeling that it was, but didn't see it when I looked back over my release notes (I only found the copy multiple), and I can't test it here at work (locked down machines, so can't install it).
