### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by MannyDo** [benrhughes/todotxt.net#321]
When I press "x" on a task, I expect the “highlight” move to the next, but instead of that, it always jump to the first line of the todo list. I can easily lose my focus. What do u guys think?

**Comment by cy2k** [comment]
I notice that at times as well, the behavior seems to be different based on which type of Sort view I'm using.  I'd be curious to find out what the actual logic is for where the focus moves to after hitting "x."

**Comment by benrhughes** [comment]
This sounds very similar to #241, which should have been fixed a long time ago by #239. Which version of todotxt are you using?

**Comment by alshort** [comment]
I have just encountered a similar bug with a fresh install of todotxt.net. Whenever I press 'x', with any sort or filter applied, it toggles the task completion state, but also opens up the Options dialog. 

I've used todotxt.net previous on a different machine (older version of the program) and it worked fine, but this is new on me.
