### ISSUE TITLE
minimize to tray by close button

### ISSUE THREAD

**Issue by PKEv** [benrhughes/todotxt.net#324]
minimize to tray by close button is very convenient functionality

**Comment by TBurkert** [comment]
Yes please! This is the only feature I'm really missing in todotxt.net.

**Comment by benrhughes** [comment]
You can already minimize to the tray (once you enable the option) using the minimize button. Could you explain why you need to be able to do it with the close button as well?

**Comment by smaugfm** [comment]
Some people are just used to closing programs unless they are heavy to start again which is the case. But it is much more handy to keep it always in tray, no matter what. I would make it run on windows startup and always have it in my tray like a service. I suggest adding "close to system tray" option not to confuse users who don't expect closing to tray.
