### ISSUE TITLE
Feature:  A request for the application to be in a sticky note format

### ISSUE THREAD

**Issue by princektd** [benrhughes/todotxt.net#327]
I have found the todotxt.net very useful and helpfull.
I usually have it always running, and also added it to registry to make it start up automatically when Windows starts up.
The only thing I had a problem with is that, for an always running 'todo' notes, I felt it would have been better it I could somehow STICK it to my desktop and leave it behind all the other windows until I needed it (the way the Sticky Notes gadget behaves), rather than as a  windowed, application like interface.

**Comment by benrhughes** [comment]
Hi,
Thanks for thw suggestion, however this is not a feature that I think we'll
implement.

In glad you find the app otherwise useful :)

Cheers,

Ben

**Comment by princektd** [comment]
Thanks for the fast reply.
Sorry to hear that. Anyway, I'll see what I can come up with.
I had made a simple gadget for myself some time back, I still have the gadget template somewhere around... It is the todo.txt formatting and this application's various options that I have no idea how to implement...
Anyway, thanks again.
