### ISSUE TITLE
Project still active ?

### ISSUE THREAD

**Issue by padr** [benrhughes/todotxt.net#333]
I recently downloaded the todotxt application for Windows and it is really nice . It seems to be sometime since the application has had any updates and the activity here is also quiet. Is this project still active ?

**Comment by benrhughes** [comment]
It is still active, however it's a fairly stable so there's not a lot of
changes. I have some pull requests queueing up so I'll probably do a new
release in the next month or so.

Cheers,

Ben

**Comment by padr** [comment]
Great - thanks Ben for such a speedy response

Padraig
