### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by tommu319** [benrhughes/todotxt.net#336]
I know the definition of "threshold" in normal English, but am a tad stumped as relates to its use in Simpletask and/or todo.txt.

Can someone help me please?

**Comment by mjdescy** [comment]
I think "threshold" is a weird term for it, too. It's really a start date. Or a "don't start until" date. Adding threshold dates is a way to indicate "future tasks". A threshold date is formatted as: t:yyyy-mm-dd.

The relevant definition of "threshold" is: a level, point, or value above which something is true or will take place and below which it is not or will not.

**Comment by tommu319** [comment]
OK, thanks, that makes it as clear as mud. LOL Seriously though, I do now
understand.
