### ISSUE TITLE
Intellisense when typing fast

### ISSUE THREAD

**Issue by aldanor** [benrhughes/todotxt.net#337]
When typing something like this fast:

```
some task +
```

Then IntelliSense would be closed before you can see it. The reason being, I think, depressing `Space` very shortly after you type `+`, so the window shows up on `+` but then disappears upon keyup event. 

Possible fix, I guess (need to double check anyhow): for intellisense box, ignore keyups whose keydowns happened before the intellisense box became visible?

**Comment by benrhughes** [comment]
Maybe I'm misunderstanding, but it sounds like you're hitting <space> and
<+> at the same time. I don't think that's something that the app needs to
cater for.

Cheers,

Ben

**Comment by aldanor** [comment]
It's very common if you're a fast typer -- for keyup up events to overlap with keydown events for a small fraction of second (maybe a few milliseconds). You're not typing them "at the same time", just in a very quick succession.

To illustrate this, try holding SHIFT and press "SPACE +" very fast -- you'll see the intellisense popup blink and disappear. Whereas if you type it slower if would stay.
