### ISSUE TITLE
Unnecessary hotkey change / revert back to "Windows logo + Alt + T"

### ISSUE THREAD

**Issue by Riparian** [benrhughes/todotxt.net#338]
The hotkey to show/ hide the todotext.net window has been for many years (and according to the help documentation it is still): “Windows logo + Alt + T”. 
On 6 th September 2017 the key combination was changed from “Windows logo + Alt + T” to “Ctr + Alt + M”.  This seems (highly) unnecessary because there is no conflict with current windows keyboard shortcuts (see https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts). Instead it creates a new conflict with a keyboard shortcut in MS Word which also uses (Ctr + Alt +M) to insert comments. Therefore I suggest to revert this back to the original behavior (or to give a good reason for this e.g., hat the old key-setting conflicts with another official windows hotkey). Alternatively, the key-combination could be made 'editable' for users even though I am not sure that this would be worth the hassle.

**Comment by benrhughes** [comment]
Hi,
Please see #294. Quite a few people reported it clashing with a default Windows 10 binding, which is why the change was accepted. 

Finding a binding that is unique across applications is nigh-on impossible, unfortunately.

**Comment by Riparian** [comment]
Thanks for letting me know and sorry for missing to read #294. For some reason I couldn't produce any effect when using the old hotkey on a Windows 10 system, so it might be that this reported conflict might be some special case. Of course, ms word users as myself who use "Alt + Ctrl + M" a lot to review & annotate a lot are another special case. Anyhow, I fully agree that finding a unique still unused hotkey combination is an impossible mission (as impossible as trying to find out which hotkey combinations affects more users.) In any case, it would be good to update the information about the hotkey in the help...

**Comment by jucor** [comment]
@Riparian Help updated in #400 :)
