### ISSUE TITLE
I cant figure out how to edit and save a new task from the top textbox. Could the instruction in the help file be clearer on this. The -N  just  enters a N in the entry or deletes the entry in text box -- it does not  move the entry to the task list.

### ISSUE THREAD

**Issue by jsb111** [benrhughes/todotxt.net#339]
The  enterkey is not moving  the text entrys from the textbox to the  tasklist.

**Comment by benrhughes** [comment]
Type in the text box and hit enter to create a new task.
With the task selected in the list, press 'u' or F2, or double-click on it
to edit it. Press enter when done editing.

**Comment by jsb111** [comment]
Hi Ben

I am finding that both my text “enter key” and numeric “enter  key” do not save the the text box entry  to the task list.

Reloaded the program  and am now resetting my computer.

**Comment by jsb111** [comment]
After my reboot and reload  I am still finding the same thing the enter key is not functioning correctly.  I ‘ll enter this issue on git hub.

 

From: Steve [mailto:jsb257@gmail.com] 
Sent: Thursday, October 26, 2017 2:08 PM
To: 'benrhughes/todotxt.net'
Subject: RE: [benrhughes/todotxt.net] I cant figure out how to edit and save a new task from the top textbox. Could the instruction in the help file be clearer on this. The -N just enters a N in the entry or deletes the entry in text box -- it does not move the en

 

Hi Ben

I am finding that both my text “enter key” and numeric “enter  key” do not save the the text box entry  to the task list.

Reloaded the program  and am now resetting my computer.

**Comment by jsb111** [comment]
I find that the "enterkey"  on my windows 10  desktop does  not move the  textbox entry  to the task list.
it does nothing  -- I turned on the error log  and  while other activities showed up  the "enterkey" did not.

**Comment by benrhughes** [comment]
There's an option called "Use Ctrl-Enter to create new task". Please make sure that this is disabled.
