### ISSUE TITLE
Archiving non-functional

### ISSUE THREAD

**Issue by mrdan** [benrhughes/todotxt.net#340]
Using version 3.3.0.0 on windows 8.

Any time I try to archive a completed item, either by hitting 'A' or using 'File-> Archive Completed Tasks', the program just displays the options window. I have an archive file set, and the file exists. The task is never archived and the selected archive file is empty. The todo.txt and todo_archive.txt files are in the same directory. The application has no problem writing to the todo.txt file.

**Comment by benrhughes** [comment]
Hi @mrdan,
We've recently had a change to the archive behaviour (implemented by @vain0). I wonder if it has accidentally introduced a bug. 

@vain0 do you have time to take a look at this issue?

Cheers,

Ben

**Comment by vain0** [comment]
Hello. I will check the behavior before long. Note: The PR in question is #312 .

**Comment by mrdan** [comment]
I notice you have 'done.txt' hardcoded in [this file](https://github.com/benrhughes/todotxt.net/pull/312/files#diff-f89b5bac9a420e4996a738f07f156e7d). I added a 'done.txt' to the same dir as my todo.txt and archiving works now!

**Comment by benrhughes** [comment]
@mrdan did you have the 'auto select archive path' option set? If yes, then it expects a done.txt to exist. Perhaps what it should do, @vain0, is create a done.txt if the option is enabled but the file doesn't exist?

**Comment by mrdan** [comment]
Yeah, looks like that was enabled. Maybe if that option is enabled the 'Archive File'' directory select option could be changed to point to the created done.txt or disabled to indicate it won't be used?

Thanks for the help anyway!

**Comment by vain0** [comment]
I see. It's unsure for users that archive file path is ignored and "done.txt" is used when auto-select is enabled, which was the introduced problem.

@mrdan wants to use todo/todo_archive pairs rather than todo/done pairs, no? If so, it may be nice if the app finds "<path-to-todo>/<archive-file-name>" as auto-selected archive file.

> Perhaps what it should do, @vain0, is create a done.txt if the option is enabled but the file doesn't exist?

It sounds useful, but the app should tell the user that done.txt is used. In my opinion, warning if auto-selected done.txt is missing is simple and sufficient.

**Comment by mrdan** [comment]
My problem was that I wasn't aware 'done.txt' was the standard expected filename. I think I ticked 'Automatically select archive **path**' because I thought it might cause the app to use my selected archive filename automatically in the same path as my todo.txt

I think my actions were something like: 

1. tried to archive - options popped up
2. tried ticking 'auto select archive path' - options still popped up
3. tried manually selecting path - saw that i had to create a file to select
4. created todo_archive and set path to that - options still popped up

A warning or similar that when 'auto select archive path' is checked a 'done.txt' file is expected in the same path as todo.txt would have given me more of a hint of the problem at least
