### ISSUE TITLE
Project/Context Drop Down - auto select when single option

### ISSUE THREAD

**Issue by RayDrew49** [benrhughes/todotxt.net#341]
Hi,

On the project/context auto suggestion drop-down, would it be possible to auto select when there's only a single remaining option so that hitting the return key would select it rather than having to hit the down arrow key to select it manually first?

I'd find that really handy.

Love the app.

Many thanks,

Ray

**Comment by oldmankit** [comment]
I've got a related suggestion. 

At the moment, to select an auto-suggestion from the drop-down list, you have to press an arrow key first, and then 'tab' to auto-complete. However it would be so much easier if you could just press 'tab' to accept the first suggestion (regardless of whether there are one or more). This would be more consistent with my experience with auto-complete in other apps, and it's what I am finding myself doing naturally. However currently 'tab' cycles to the next pane in the app. I think this 'tab' functionality should be disabled while actually editing an item, to allow it to be used purely for auto-complete.

**Comment by benrhughes** [comment]
Thanks for the suggestions. todotxt.net is in maintenance mode and no new features are likely to be added.
