### ISSUE TITLE
Naming filters

### ISSUE THREAD

**Issue by BruceHarrison** [benrhughes/todotxt.net#342]
Greetings,

Is it possible to name filters?  A filter name of @wife or +MeanginfulProjectName is more meaningful than "Apply  Meaningful Filter 1" (or "Filter #: 3" in the status bar).   

Thanks.

**Comment by shulist** [comment]
Why could you not just use the filter text as the title, for single word filters:
`Filter: @phone`
Or for longer filter text just use first x characters and an ellipses:
`Filter: @phone +Pr...`

I routinely fill out five or six filters and then promptly forget what was in them. This might act as a reminder.
