### ISSUE TITLE
Archiving not working

### ISSUE THREAD

**Issue by Kaishiyoku** [benrhughes/todotxt.net#345]
Hello,

when I'm clicking "File > Archive Completed Tasks" the options dialog is being opened instead.

**Comment by mjdescy** [comment]
If "Archive Completed Tasks" is called, and no archive file has been set in Options, the Options screen will open. Fill in the "Archive File" setting in Options, and archiving will work (without bringing you to Options again) going forward.

**Comment by Kaishiyoku** [comment]
Got it working. Sorry for any inconveniences.
