### ISSUE TITLE
Colored priorities lines or letters

### ISSUE THREAD

**Issue by Riko01** [benrhughes/todotxt.net#346]
Hello, 

I thought it could be a nice feature to have colored lines or just the priority markers to be of different colors for easier recognition. 

Something like this: http://todotxt.org/images/todotxt-apps_lrg.png or http://rtalbert.org/assets/images/2017-07-10/todo-ss.png

If you would find time to implement this it would be great. 

Thank you and wish you everything the best.

**Comment by Li-An** [comment]
+1

**Comment by Kamul-PL** [comment]
I agree. And separate colors for description, dates, projects, contexts would make task list much more readable.

**Comment by benrhughes** [comment]
todotxt.net is in maintenance mode and no new features are likely to be added.
