### ISSUE TITLE
DONE filter does not work

### ISSUE THREAD

**Issue by j-xella** [benrhughes/todotxt.net#349]
I have created a filter that consists of one line only with the word "DONE" (without quotes) in it. In my understanding, such filter is supposed to show me completed tasks only. Yet nothing shows at all when I select this filter. I have another filter which is just "-DONE", and it works OK, filtering out the completed tasks. My todo.txt has both completed and incomplete tasks.

Todotxt.net version 3.3.0.0

**Comment by j-xella** [comment]
Probably related to #284

**Comment by benrhughes** [comment]
This is covered by #305 which will be in the next release

**Comment by keighrim** [comment]
This is actually a bug in the `DONE` filter. I'll open a PR.

**Comment by muteboy** [comment]
I have this problem too. When will the new release be out?
