### ISSUE TITLE
Archive file naming convention

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#350]
I use a number of files to manage my activities. **Having ToDo.Txt dump all completed tasks into one common file is not workable** in the long term. Constantly changing the archive file is a pain and something I forget to do regularly.

Would it be possible to enable ToDo.Txt to write out an archive file with the following file name:

> CurrentActiveFilename_done.txt

So that no matter what file you have open it will be archived properly in the correct related file. This archive file should be in the same directory as the active file and is created, if it does not exist, (assuming you have write access).

**Comment by benrhughes** [comment]
This functionality currently exists, although it's implementation is sub-optimal. 

If you have each of your todo.txt files in a different folder with a corresponding done.txt, and select the 'Automatically select archive path' option, archiving will use that done.txt.

I think supporting (and creating if it doesn't exist <todofilename>_done.txt is a good idea - it allows you to store multiple todo files (and their archives) in a single directory.

**Comment by benrhughes** [comment]
todotxt.net is in maintenance mode and no new features are likely to be added.
