### ISSUE TITLE
Current file name on status line?

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#351]
In working with multiple ToDoTxt files in any given period I am forever forgetting just what file I have open. Would it be possible to have the current file name appear in the bottom status line? Something as simple as:

> ...Due Today: 5 | Overdue: 3 | File: **CurrentOpenFile.txt**

 Thanks,

**Comment by shulist** [comment]
While I am not a Windows developer it seems that the usual format for this in Windows is to appear in the upper left corner in the following format:
`CurrentFileOpen.txt -  AppName`

So for ToDoTxt.net it would be as follows:
`CurrentFileOpen.txt -  ToDoTxt.net`

**Comment by shulist** [comment]
Sorry closed by mistake...

**Comment by benrhughes** [comment]
todotxt.net is in maintenance mode and no new features are likely to be added.
