### ISSUE TITLE
Need for a Wiki

### ISSUE THREAD

**Issue by prakhargahlot** [benrhughes/todotxt.net#353]
With the app having increased in features over time, there needs to be a Wiki that users can go to for help regarding features.

It might (and ought to) also include the basic formatting principles and idea about todo.txt

**Comment by benrhughes** [comment]
I agree with the first part but not the second. The main todo.txt site
(which is already linked) covers the philosophy and formatting rules.

**Comment by benrhughes** [comment]
Wiki page for help created - https://github.com/benrhughes/todotxt.net/wiki/help
