### ISSUE TITLE
 Adding very simple Markdown-like features

### ISSUE THREAD

**Issue by Oroumov** [benrhughes/todotxt.net#362]
Hi again, 
Continuing my Christmas wishlist :)

Feature : 
* Adding very simple Markdown-like features

Description :
* While not breaking Gina's original format, have you considered simple tags for a few visual improvements (as an optional setting maybe for purists to not be disturbed) ?
The first thing I'm thinking of is lists, which I use heavily in a single line mode today like this :
**Action 152 --Call John for info --Review with Jack due:2018-08-13**
But it could show as :
**Action 152**
**-- Call John for info**
**-- Review with Jack**
**due:2018-08-13**
In plain text, this markup would be harmless, so that other apps plugged to the same file may simply ignore it, and in your app, only the render would be impacted.
Maybe you have already thought about this and rejected it for a good reason :) !

Thanks,
Nicolas.

**Comment by benrhughes** [comment]
As much as I love markdown, I don't want to move away from the simplicity
of the todo.txt format. There are lots of other todo formats that cover
that sort of thing.

Cheers,

Ben

**Comment by Oroumov** [comment]
Hi Ben, 
Thanks for answering, I kind of expected this answer to be honest, but it was worth asking.
Cheers, 
Nicolas.
