### ISSUE TITLE
Small enhancement to filters to create a "Search"-like feature

### ISSUE THREAD

**Issue by Oroumov** [benrhughes/todotxt.net#363]
Hi again (...)
One more suggestion here :

Feature : 
* Small enhancement to filters to create a "Search"-like feature ?

Description :
* The closest thing we have now from a Search function is to :
  * Type F to jump in filters
  * Click on "Clear Active" to remove the current filter (or "Alt-C", or "Ctrl-A, Delete")
  * Type in your new search string
  * Press Enter Twice

I've thought of a very simple improvement : would you consider implementing the ubiquitous Ctrl-F feature and make it jump to the filters AND clean the "Currently Active Filter" at once ?
The sequence would now be :
  * Type Ctrl-F
  * Type in your new search string
  * Press Enter Twice

And voilà ! An immediate "search" function, all without touching the "F" behavior for everyone.

Thanks,
Nicolas.

**Comment by benrhughes** [comment]
Hi,
The current way to do this is to use '0F' - '0' clears the filter, F opens
the dialog. To me this is as easy as Ctrl-F would be.

Cheers,

Ben

**Comment by Oroumov** [comment]
Hi Ben, 
I'm ashamed now ! I cycle between active filters constantly, completely forgot about "0" !!
0F is perfect for this, sorry for wasting your time :)
Cheers, 
Nicolas
