### ISSUE TITLE
Adding a custom shortcut for todotxt app

### ISSUE THREAD

**Issue by Oroumov** [benrhughes/todotxt.net#364]
Hi again, 
One more feature suggestion here :

Feature : 
* Adding a custom shortcut for todotxt app

Description :
* Would it be possible to invoke the todotxt app with a system wide shorcut ?
I've seen it mentioned here and there in the other posts (especially the ones talking about the earlier shortcut change), but can't seem to find it officially logged
A user defined shortcut would be a game changer if you spend your time adding/updating your action list.

Thanks,
Nicolas.

**Comment by benrhughes** [comment]
If you enable 'Minimize to system tray', then you can use Win-Alt-T to
hide/show the app.

Cheers,

Ben

**Comment by Oroumov** [comment]
Hi Ben, 
I confirm the default shortcut works flawlessly with Minimize to system tray (Ctrl-Alt-M in my case).
But as someone mentioned in another topic, often it conflicts with some other shortcuts that I can't change either in Windows (sometimes) or in some commercial software (always) which are full of predefined shortcuts of all kinds.
So I wanted to officially raise the question of the "customizable" part of the shortcut. :)
Cheers,
Nicolas

**Comment by benrhughes** [comment]
I agree that this would be the ideal solution :) If I'm honest I don't have
the motivation to implement the changes myself, but if someone else does
I'd be happy to accept the PR.

Cheers,

Ben

**Comment by benrhughes** [comment]
At this stage todotxt.net is in maintenance mode and no new features are likely to be added.
