### ISSUE TITLE
Indent second and following lines of word wrapped tasks?

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#365]
I usually have two or three ToDoTxt windows open concurrently and have them as side by side as narrow columns. In order to see all task details I usually turn on word wrap. but with word wrap on all lines are left aligned. 

In order to visually highlight the first line of a task would it be possible to indent the second and succeeding lines?

**Comment by benrhughes** [comment]
Thanks for the suggestion. At this stage todotxt.net is in maintenance mode and no new features are likely to be added.
