### ISSUE TITLE
Feature request: quick-filter / quick-search functionality always available in UI

### ISSUE THREAD

**Issue by celmi** [benrhughes/todotxt.net#366]
I'm finding the filter-function a bit tedious to use for spontaneus search-activities (for example, if I want to check wether a task already exists or needs to be written) . I'd love to be able to write a search-term into a textbox that is always present somewhere in the user-interface, immediately filtering out any tasks that contain this term (similar to the quick-search in thunderbird, where I can filter out mails from the mailbox I am currently looking at). 

p.s. thanks everyone involved for this awesome tool!

**Comment by Kamul-PL** [comment]
I agree with celmi. Such a quick-search would be highly desirable. Or at least any kind of search (besides filtering). Or maybe there is search possibility, but I can't find it? (I am a new user of todotxt.net).

A also wanted to admit, that even if I've just started my adventure with this app, I think it's great. It has all what I like: its lightweight, useful and all relevant things could be done using just keyboard. Big thanks to developers!

**Comment by JasonDavidBeck** [comment]
Vim-style quick-search would be an awesome addition.  

     </> to enter search mode
     <Enter> to enter search term
     <n> or <N> to go to next/previous
     <ESC> to exit search mode

Matching instances of search term are highlighted on the fly as the search term is entered.

Thanks!

**Comment by benrhughes** [comment]
Thanks for the suggestions. At this stage todotxt.net is in maintenance mode and no new features are likely to be added.
