### ISSUE TITLE
Option to require a priority

### ISSUE THREAD

**Issue by schultzter** [benrhughes/todotxt.net#370]
I'm getting used to todotxt.net and so far so good. 

One thing that would make it more efficient for me to would be to start every new task with a priority. 

To that end I would either automatically go into a priority drop down (like the project and context drop downs) when you create a new task and add the open and closing parenthesis automatically. 

To make it more clear, make the open parenthesis key, (, the keyboard short cut to create a new task with priority! But keep the N key a short cut to create a new task without priority. 

Thanks,

**Comment by hellium** [comment]
Since pull request is merged, I believe this issue can be closed.
