### ISSUE TITLE
Release 3.3.1 (beta) what things need to be tested?

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#377]
I downloaded and started to go through the testing of 3.3.1 (beta) but could not find any release notes. Its not clear to me exactly what features and bugs need to be tested. With all of the prior issues now closed and only 6 bugs left open it's difficult to determine the scope of testing. 

Is it possible to tag issues that are worked into this release? 

Any suggestions?

**Comment by benrhughes** [comment]
Sorry, I should have been clearer about the testing. Here is the list of changes:

https://github.com/benrhughes/todotxt.net/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+closed%3A2017-09-23..2019-01-20+

The most useful thing to do, though, is just to use it day to day for a while. I'm mostly interested in knowing that we haven't unintentionally broken existing functionality.

Cheers,

Ben


---- On Sun, 10 Feb 2019 02:15:35 +1100 notifications@github.com wrote ----

I downloaded and started to go through the testing of 3.3.1 (beta) but could not find any release notes. Its not clear to me exactly what features and bugs need to be tested. With all of the prior issues now closed and only 6 bugs left open it's difficult to determine the scope of testing.

Is it possible to tag issues that are worked into this release?

Any suggestions?

**Comment by shulist** [comment]
I have been using the 3.3.1 beta since you released it and will continue to do so. I'll also specifically test the items in the release.

**Comment by shulist** [comment]
Oops sorry about closing this mis-clicked.
