### ISSUE TITLE
Some help to keep the development of TDT moving forward

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#378]
Recently @benrhughes in issue #376 identified that he has decided to put TDT into a maintenance mode. Ben was the creator and has been the support for this great application for the past decade but, reading between the lines, I am guessing that Ben just wants to move on. 

While I am no programmer (I will, however, volunteer in any way I can) I suspect that there might be some out there that might be able to take over the responsibility of managing this code and allow the community to help it evolve in the future. I, for one, do not want it to be in maintenance mode as I believe there  are many things that it could achieve. 

Will anyone in this community be willing to step up and give Ben the break he deserves?

**Comment by hellium** [comment]
Why not? I will dedicate some time into outstanding bugs and hopefully can contribute before next release.
> I believe there are many things that it could achieve

On the other hand I agree with @benrhughes , this is minimalist app and new features must be considered with care. Let's discuss what features we can add without breaking "minimalist" approach.

**Comment by shulist** [comment]
@hellium great news thanks for stepping up.

I too agree that the minimalist approach would be something to be considered.  I'll give some thought to developing an outline that might help guide the development and evolution of the application going forward though @benrhughes it would be great to get your current thoughts on this?
Right now Ben released TDT 3.3.1 and I am doing some testing on it. The [release content can be seen here](https://github.com/benrhughes/todotxt.net/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+closed%3A2017-09-23..2019-01-20+)

**Comment by benrhughes** [comment]
I appreciate both of your efforts and enthusiasm.

My thoughts are as I stated earlier. The app is done bar bug fixes, for which I'm happy to accept issues and PRs.

If someone has a proposal for a new feature and is willing to implement it, they can open an issue and discuss it. If it makes sense I'll give it the OK.

As has always been the case, if some wants to add a feature that I don't approve of, they can fork the project.

Cheers,

Ben


---- On Thu, 21 Feb 2019 02:58:08 +1100 notifications@github.com wrote ----

@hellium great news thanks for stepping up.

I too agree that the minimalist approach would be something to be considered. I'll give some thought to developing an outline that might help guide the development and evolution of the application going forward though @benrhughes it would be great to get your current thoughts on this?
Right now Ben released TDT 3.3.1 and I am doing some testing on it. The release content can be seen here
