### ISSUE TITLE
TDT 3.3.1 (beta) showing wrong version number in help file

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#380]
1. Under <Help><About> the version number has not been changed to 3.3.1
2. The help file needs to be updated for the latest changes. 
3. Does the help file source its data from the ReadMe.md? Are the two linked?
4. Update the copyright notice?
5.

**Comment by aubreyz** [comment]
What confused me initially is that on the beta page https://github.com/benrhughes/todotxt.net/releases/tag/3.3.1-beta

the one download is in fact not a beta, but the other is even though both are under the header "Pre-release of 3.3.1"
