### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by aubreyz** [benrhughes/todotxt.net#389]
Not really an "issue" but it is. 
This is by FAR the greatest and best manager of todo.txt on Windows, and it would be hugely sad if it were to die a death -- even to the point of not making available a compiled version of the latest portable beta (with the threshold dates addition) and fixing occasional bugs.  I'm not going to be a capable programmer here -- but someone must be....

Don't die please..

**Comment by benrhughes** [comment]
Rumours of todotxt.net's death have been greatly exaggerated ;)

I've been planning to get the lastest official release (including portable) out for a few weeks but life keeps getting in the way. I'll get it done this weekend.

Overall, I'm confused about people wanting new releases. It's pretty good at what it does, isn't particularly buggy and people like using it. Unless the underlying format changes, or the .Net framework gets EOL'd, it will continue working just fine into the future.

Cheers,

Ben


---- On Wed, 14 Aug 2019 21:52:46 +1000 notifications@github.com wrote ----



Not really an "issue" but it is.
This is by FAR the greatest and best manager of todo.txt on Windows, and it would be hugely sad if it were to die a death -- even to the point of not making available a compiled version of the latest portable beta (with the threshold dates addition) and fixing occasional bugs. I'm not going to be a capable programmer here -- but someone must be....

Don't die please..

**Comment by benrhughes** [comment]
Release of 3.3.1 is done. Closing.
