### ISSUE TITLE
3.3.1 still incorrect portable compile

### ISSUE THREAD

**Issue by aubreyz** [benrhughes/todotxt.net#390]

**Comment by aubreyz** [comment]
On the latest portable download of 3.3.1 the help about still shows 3.3.0, and all the threshold stuff (by far the most useful recent addition) has disappeared. The problem may be with the actual link in the current download page because the file is dated 2017. So we need a valid link to the current portable download which is currently not correct. 

See the first link on the releases page https://github.com/benrhughes/todotxt.net/releases

**Comment by mminnick** [comment]
Can confirm, the version in the portable download is 3.3.0 and not 3.3.1.

**Comment by benrhughes** [comment]
Ok, thanks. There must be an issue with the build script that creates the portable package. I'll take a look.


---- On Mon, 19 Aug 2019 22:31:49 +1000 notifications@github.com wrote ----



Can confirm, the version in the portable download is 3.3.0 and not 3.3.1.

**Comment by smaragdus** [comment]
I have just seen that the portable releases of versions [3.3.0](https://github.com/benrhughes/todotxt.net/releases/tag/v3.3.0) & [3.3.1](https://github.com/benrhughes/todotxt.net/releases/tag/v3.3.1) are exactly the same:

**todotxt.net 3.3.0:**

```
Name: todotxt-portable.zip
File Size: 372691 Byte(s) (363.96 KB)
Modified Date: 2017-09-23 14:31
MD5: 65a542d7bd9ad2d9830d9e4d9a1bf781
SHA1: 96d1394e458d57ec6bb0556e7da8819ca0fc3b8c
SHA256: 1c0fe0d37d5519af0e701aebcd47ee17a39751386b18f8e216976c8f75bcf636
SHA384: 78aca46b3204c7899068614d16c302101b4f56eda88dc0ad86a8922d1ab501e986698005b88d938d78684cd6199ade84
SHA512: 5b8394bac4570c473f8afc29d02d18978fb4b2c9c429d996cf718d91aa042f8af478ca9930794a508e138354a3f44548ec2be32d4f84740d23243f7ffeb58176
```

**todotxt.net 3.3.1:**

```
Name: todotxt-portable.zip
File Size: 372691 Byte(s) (363.96 KB)
Modified Date: 2019-08-18 04:30
MD5: 65a542d7bd9ad2d9830d9e4d9a1bf781
SHA1: 96d1394e458d57ec6bb0556e7da8819ca0fc3b8c
SHA256: 1c0fe0d37d5519af0e701aebcd47ee17a39751386b18f8e216976c8f75bcf636
SHA384: 78aca46b3204c7899068614d16c302101b4f56eda88dc0ad86a8922d1ab501e986698005b88d938d78684cd6199ade84
SHA512: 5b8394bac4570c473f8afc29d02d18978fb4b2c9c429d996cf718d91aa042f8af478ca9930794a508e138354a3f44548ec2be32d4f84740d23243f7ffeb58176
```

**Comment by benrhughes** [comment]
Fixed

**Comment by aubreyz** [comment]
Works great - thanks ben
