### ISSUE TITLE
Keyboard shortcuts for increasing/decreasing due date broken

### ISSUE THREAD

**Issue by remingtonsmith** [benrhughes/todotxt.net#395]
The Ctrl+Up shortcut deletes the entire task if you ever try to increase the due date beyond the present date.
The Ctrl+Down shortcut erroneously appends "t:[date]" to the end, which does not conform to Gina's spec.  The syntax should be due:[date].

Neither Ctrl+Up or Ctrl+Down recognize the due:[date] in a task and modify that date.  They both add/modify t:[date], which is not recognized in Gina's spec.

**Comment by aubreyz** [comment]
due: and t: are totally different things. Both are correct parts of the original spec and widely used extensions. 

At least here the task does not delete with Ctrl+Up. Firstly this acts on the threshold date not the due date. You must have "Hide Future Tasks" ticked. 

Ctrl+Alt+Up or Ctrl+Alt+Down act on the due date as expected.

**Comment by remingtonsmith** [comment]
Thanks aubreyz.  It appears I was using the wrong shortcuts to increase/decrease the due date as I read the help shortcut list too quickly.  Now that I'm using the right shortcuts:

- Ctrl+Alt+Up does appear to correctly act on the due date as expected.
- **Ctrl+Alt+Down, however, is nonresponsive for me.**

As to the threshold issue, I was not aware of that feature.  You were correct—I had hide future tasks ticked.  However, the help documentation should list the Ctrl + Up and Down shortcuts for threshold.  There is considerable documentation on the spec that omits any reference to threshold, and, despite using this program for years, I had to hunt for information about it.

**Comment by bubonicfred** [comment]
I just came here to second that the help page doesn't list the `Ctrl+up` `Ctrl+down ` shortcuts. Should a separate issue be made?

**Comment by daveliao** [comment]
@bubonicfred - I don't think a separate issue would help (since this issue is still open).

**Comment by remingtonsmith** [comment]
Go ahead and start a new issue for the documentation.  Everything is working fine now that I disabled the conflicting shortcuts in AutoHotKey.  But, the shortcuts and threshold should definitely be better documented.
