### ISSUE TITLE
[CTRL]+[UP ARROW] deletes a task

### ISSUE THREAD

**Issue by f-leoni** [benrhughes/todotxt.net#398]
Version of TODOtxt.net is 3.3.1.0 on Win 10

When I issue [CTRL]+[UP ARROW] on a task which is highlighted on the list, then that task is deleted from the list without asking for a confirmation.

Thanks,
F.

**Comment by benrhughes** [comment]
Hi,
In all likelihood you have a filter enabled that is filtering the newly prioritised item out of the list. Hopefully clearing your filter should make the task reappear.


Cheers,


Ben




---- On Sat, 07 Dec 2019 02:32:42 +1100 notifications@github.com wrote ----



Version of TODOtxt.net is 3.3.1.0 on Win 10

When I issue [CTRL]+[UP ARROW] on a task which is highlighted, then that task is deleted from the list without asking for a confirmation.
I don't think [CTRL]+[UP ARROW] was a documented keystroke.

Thanks,
F.

**Comment by f-leoni** [comment]
You are right. I had "Hide future tasks" filter enabled without even knowing. Disabling the filter all is working as espected.
Thanks for the support and keep up the good work, I've been using todotxt.net everyday for a couple of years now and I think it's great.

Best,
F
