### ISSUE TITLE
newbie question - how do I compile portable version?

### ISSUE THREAD

**Issue by fleapower** [benrhughes/todotxt.net#404]
As the subject line says, I am a complete newb when it comes to using Visual Studio.  I figured out how to make some changes to the code to customize it for my use, and I've been able to compile it, but it compiles as the non-portable version.  How do I compile it as the portable version?  Thanks!

**Comment by jdckr** [comment]
You need to call msbuild.exe like here https://github.com/benrhughes/todotxt.net/blob/e4c0c762be15ebbd20f10f63059c7193f28e3fc2/Installer/Create-Installer.bat#L1

If you just need the portable version you might want to remove the CreateSetup step, as this requires additional dependencies
https://github.com/benrhughes/todotxt.net/blob/e4c0c762be15ebbd20f10f63059c7193f28e3fc2/Installer/Build.xml#L21

**Comment by fleapower** [comment]
Thanks!
