### ISSUE TITLE
Full Path Visible in Window Title

### ISSUE THREAD

**Issue by qalisto** [benrhughes/todotxt.net#405]
For those of us who use atypical filenames or store in non-default paths, this would save us time from having to search in the DIRs to recall the location of the file in use.  

Thanks.

**Comment by shulist** [comment]
This was suggested some time ago in https://github.com/benrhughes/todotxt.net/issues/351 but for some reason was closed.

**Comment by daveliao** [comment]
Ah, the "some reason" is that the original author has put this project in maintenance mode (only break/fix patches are being accepted).
