### ISSUE TITLE
show interface screenshot

### ISSUE THREAD

**Issue by higimo** [benrhughes/todotxt.net#406]
plaese in site and README.md

**Comment by daveliao** [comment]
Nice suggestion @higimo!

@benrhughes - I volunteer myself as tribute. Can I come up with some cheeky (and possibly realistic) tasks to demo the todotxt.net user interface? 😅 Since the app is in maintenance mode, there shouldn't be a need to update the screenshot often.

**Comment by benrhughes** [comment]
Sorry for the extremely late reply. I'll happily take pull requests that update the readme.
