### ISSUE TITLE
Suggestion: move tasks between files

### ISSUE THREAD

**Issue by elig0n** [benrhughes/todotxt.net#409]
Would you implement a feature to move tasks between todo files so one doesn't have to edit them manually?

**Comment by daveliao** [comment]
@elig0n Interesting, do you have multiple todo.txt files? If so, what do you use each one for?

**Comment by elig0n** [comment]
> @elig0n Interesting, do you have multiple todo.txt files? If so, what do you use each one for?

I usyally divide them by subject. For example programming projects, videos to watch, books to read etc...

**Comment by remingtonsmith** [comment]
I track tasks I've assigned to others by tagging it in +Initials.  Each of those users uses their own version of todotxt.net.  While I can manually open their todo.txt file, it would be much more efficient if I could toggle between those different lists using a tabbed interface and right click a task to move it to another user's list.

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
