### ISSUE TITLE
[Feature request] Dark theme

### ISSUE THREAD

**Issue by opusforlife2** [benrhughes/todotxt.net#411]
Hi. I would like a simple dark theme toggle that just switches to a dark background and light text. Nothing fancy.

**Comment by jdckr** [comment]
Hi,
I lately created a fork having a dark theme. It doesn't have a toggle, though.

![Image](https://github.com/jdckr/todotxt.net/raw/dev/main.png)

**Comment by opusforlife2** [comment]
This looks great!

**Comment by 0x4a** [comment]
This look real nice @jdckr (also the added features),
are there any plans for a binary release soon?

**Comment by jdckr** [comment]
@0x4a There you go: https://github.com/jdckr/todotxt.net/releases/tag/todotxt-fork_v1.0

**Comment by opusforlife2** [comment]
Wow! Thanks a lot!

**Comment by fleapower** [comment]
Thanks!  I was literally just sitting down to figure out how to do this.  Do you have a record of the changes you made?  I'm just curious how you did it (for my own educational purposes).

**Comment by jdckr** [comment]
@fleapower 
Just diff my fork to upstream or check the feature branch I made https://github.com/jdckr/todotxt.net/commits/feature/dark_mode

Be aware that github shows the commits introduced by the merges as well.

**Comment by fleapower** [comment]
> @fleapower
> Just diff my fork to upstream or check the feature branch I made https://github.com/jdckr/todotxt.net/commits/feature/dark_mode
> 
> Be aware that github shows the commits introduced by the merges as well.

Thanks!  I am new to GitHub, but would like to get my feet wet.

**Comment by fleapower** [comment]
Thanks for the help.  I was able to modify your code a bit.  I have a recurring task script which uses the priority from the completed tasks.  I commented the line which removes the priority from completed tasks and recompiled it into a new portable version.

Next on the agenda is to figure out how to add menu options.

**Comment by Kamul-PL** [comment]
Nice to see that _todotxt.net_ isn't dead. Thank you very much!
By the way, does anyone use [_Simpletask_](https://github.com/mpcjanssen/simpletask-android)? I think it would be really nice to implement at least some of _Simpletask_ features in _todotxt.net_. For example tasks recurring options. Or preserving priority of finished task - useful at least in my case.
Unfortunately I don't have Android programming skills end (even worse) currently no time to change that. But I'm writing this as a suggestion in case some talented developer will have enough time and willingness to work at that. :)

**Comment by fleapower** [comment]
> Nice to see that _todotxt.net_ isn't dead. Thank you very much!
> By the way, does anyone use [_Simpletask_](https://github.com/mpcjanssen/simpletask-android)? I think it would be really nice to implement at least some of _Simpletask_ features in _todotxt.net_. For example tasks recurring options. Or preserving priority of finished task - useful at least in my case.
> Unfortunately I don't have Android programming skills end (even worse) currently no time to change that. But I'm writing this as a suggestion in case some talented developer will have enough time and willingness to work at that. :)

Yes, I use Simpletask.  This is off off the "Dark Theme" topic, but I wanted to address your thoughts.

Regarding task priority preservation, I modified jdckr's fork to do just that.  If I can figure out how to use GitHub (sorry, I really just code for myself, so I really don't know how to use  it) and do a pull request, I'll submit it.

Second, I use Simpletask Cloudless and DriveSync (free version is fine) to keep my PC's and Android's task list in sync.  I wrote a Google script which recurs all of my recurring tasks.  Do you use Google Drive?  If so, I can share the script with you and tell you how to implement it.

**Comment by Kamul-PL** [comment]
> Yes, I use Simpletask. This is off off the "Dark Theme" topic, but I wanted to address your thoughts.

Is there any better place for such a discussions, to not clutter this place?

> Second, I use Simpletask Cloudless and DriveSync (free version is fine) to keep my PC's and Android's task list in sync. I wrote a Google script which recurs all of my recurring tasks. Do you use Google Drive? If so, I can share the script with you and tell you how to implement it.

I use Simpletask cloudless and Syncthing to synchronize between Android and Windows (and sometimes Linux). It's really good solution, at least for me. But thank you very much for your offer. By the way, currently I use todotxt.net mainly for adding tasks (much more comfortable keyboard) and Simpletask to checking tasks. This way it takes care of looping recurring tasks. But if tototxt.net were support recurring tasks, some things would be even easier.

Thank you for your reply, and sorry for my late answer.

**Comment by filviu** [comment]
Any chance this will be merged back into the main app maybe behind a toggle ?

**Comment by Kamul-PL** [comment]
It would be wonderful...

**Comment by benrhughes** [comment]
Although I'm no longer taking feature requests, if someone were to send a PR for this (as mentioned, controlled via settings) I'd accept it.

**Comment by gerroon** [comment]
It would be nice if this app offers dark theme. I am not a dev so this is not something I can achieve myself.
