### ISSUE TITLE
[Feature Request] "Open todo.txt" / "Open todo.txt Folder" menu item

### ISSUE THREAD

**Issue by 0xcfff** [benrhughes/todotxt.net#414]
Sometimes it is necessary to open todo.txt file in a simple text editor and do massive changes there. For such cases, it would be nice to have possibility to open it from the application menu or alternatively open a folder that contains the file, so that than the file can be opened using a custom application from the file context menu rather than the default one.

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
