### ISSUE TITLE
[Feature Request] Navigate To function

### ISSUE THREAD

**Issue by 0xcfff** [benrhughes/todotxt.net#416]
The idea is to have something similar to VS Code "Go To" function or "Search Everywhere" Project Rider / ReSharper function. For TODOs it can work as follows:
By clicking Ctrl+T, application goes to special search mode, cursor is placed in search box. User has following options to type in and navigate:

- Plus sign and some text - the task view is switched to Group by Project mode, user is navigated to the first project matching the first entered word and the first task matching text that goes after the project name is selected
- At sign plus some text - the task view is switched to Group by Context mode, user is navigated to the first context matching the first entered word and the first task matching text that goes after the context name is selected
- Some text - current view is used, first task that have all entered words is selected

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
