### ISSUE TITLE
[Feature Request] Custom Filter Labels

### ISSUE THREAD

**Issue by quarklark** [benrhughes/todotxt.net#418]
The filter system works great, but it's hard to remember what context is active, or why I made it in the first place. I'd like to be able to give a custom label to each filter and see this displayed when it's active, so that I know the exact context I'm looking at.

Suggested solutions:

One option would be to give each preset a label field that corresponds to it. This way, I would know that this preset is called this.

Another option would be to add some kind of way to provide the label in the filter box itself, for example, if the first line starts and ends with a " character, we know that this is the label for the filter.

**Comment by shulist** [comment]
This was previously suggested under  #342 but closed for some unknown reason.

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
