### ISSUE TITLE
Ctrl + up and Ctrl + down shortcuts not listed in help documentation 

### ISSUE THREAD

**Issue by bubonicfred** [benrhughes/todotxt.net#419]
>, the help documentation should list the Ctrl + Up and Down shortcuts for threshold.  There > is considerable documentation on the spec that omits any reference to threshold, and, >despite using this program for years, I had to hunt for information about it.

_Originally posted by @remingtonsmith in https://github.com/benrhughes/todotxt.net/issues/395#issuecomment-530407468_
As stated above the keyboard shortcuts for changing a task threshold are not listed in the help documentation, this leads to confusion if the shortcuts are accidentally pressed, especially if hide future tasks is selected which will result in tasks appearing to vanish.

**Comment by shulist** [comment]
If I understand you correctly the `Ctrl-Up` and `Ctrl-Down` is not listed in software help file, as it is listed in the [ReadMe.MD](https://github.com/benrhughes/todotxt.net/blob/dev/README.md). I am guessing MD was modified at some point earlier and not included in the builds. @benrhughes I can confirm this is still missing from TDT3.3.1. I am not sure how the MD file gets translated in to the build however.

**Comment by benrhughes** [comment]
Unfortunately the embedded help and the readme are not connected in any way, so things have to be manually added to both. 








---- On Fri, 12 Mar 2021 03:52:18 +1100 shulist ***@***.***> wrote ----




If I understand you correctly the Ctrl-Up and Ctrl-Down is not listed in software help file, as it is listed in the https://github.com/benrhughes/todotxt.net/blob/dev/README.md. I am guessing MD was modified at some point earlier and not included in the builds. https://github.com/benrhughes I can confirm this is still missing from TDT3.3.1. I am not sure how the MD file gets translated in to the build however.

**Comment by chipbite** [comment]
The commands are listed in the menu, ofc. Could be in the about dialogue, that would be good.
![image](https://user-images.githubusercontent.com/559199/145007673-2fb8dabe-16a5-47e6-b12d-133318b223f2.png)
![image](https://user-images.githubusercontent.com/559199/145007755-f9f60dd9-7e7e-4f1b-a0af-92b698c7791d.png)
