### ISSUE TITLE
[Feature Request] Maintain Scrolling Position On Task Completion When Automatic Archiving Enabled

### ISSUE THREAD

**Issue by remingtonsmith** [benrhughes/todotxt.net#421]
I utilize the automatic archiving setting.  When I check something as done, the view jumps to the top of the list rather than maintaining the scrolling position.  It would be much more preferable if the scrolling position was maintained on such reloads.

**Comment by digital-carver** [comment]
Also applies to Sorted views, even without auto archiving. I have mine Sorted by Priority, which automatically puts completed tasks at the bottom. This means that whenever I mark a task as completed, the task gets pushed to the bottom of the list, and the view also jumps to the bottom with it, losing the scrolling position.

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
