### ISSUE TITLE
Task Sharing Among Multiple Users

### ISSUE THREAD

**Issue by remingtonsmith** [benrhughes/todotxt.net#423]
Does anyone use a single txt file shared among multiple users each running todotxt.net?  How have you designed your tags and filters to make this work?  I.e., users will want to be able to easily see just their own tasks.  Do you just tag each task with the initials of the assignee as a task (e.g., +RBS).  Currently, it doesn't seem like todotxt.net is sufficiently handling tasks with multiple tags.

**Comment by benrhughes** [comment]
You might get a better response if you ask in one of the todo.txt mailing lists/forums
