### ISSUE TITLE
[Feature Request] Show Completed Tasks at the End in "Context" or "Project" Sort Mode

### ISSUE THREAD

**Issue by Super3000** [benrhughes/todotxt.net#425]
Hi, I would like to ask if it could be possible to show the Completed Tasks at the End in "Context" or "Project" Sort Mode, below n/a section. This could be optional. Reason is that many completed tasks in a project make it unreadable in "Context" or "Project" Sort Mode. And archiving is not an option in the projects.

For Example like this:

**@Robert**
Write a summary @ROB
Buy paper @ROB

**@Claudia**
Computer work @CLA
CHeck opportunities @CLA

**@Thomas**
Write a summary @THO
Buy paper @THO

**n/a**
Door closed?
Nice weather?

**Completed** [this is acutally strike-strough in todotxt.net]
_Write a summary @ROB
Buy pineapples @ROB
Pay bills @TOM
Eat an apple @robjefferies_ 

Thank you very much :)
Super

**Comment by rob** [comment]
I'd like to buy the pineapples. We need organic or what?

**Comment by Super3000** [comment]
> 
> 
> I'd like to buy the pineapples. We need organic or what?

I'm sorry, rob. Your task "Buy pineapples" is already completed. But you still need to "Write a summary" (another one) and "Buy paper"... ;)

**Comment by shulist** [comment]
@Super3000 its not clear to me if you just want to get _Completed Tasks_ grouped below the listing or get rid of it completely. Based upon your comment of: `archiving is not an option` it seems to me you'd be happy with them temporarily disappearing? If so then just filter them out using `-DONE`. In most case I never really care about seeing _Completed Tasks_ myself.

**Comment by Super3000** [comment]
> 
> 
> @Super3000 its not clear to me if you just want to get _Completed Tasks_ grouped below the listing or get rid of it completely. Based upon your comment of: `archiving is not an option` it seems to me you'd be happy with them temporarily disappearing? If so then just filter them out using `-DONE`. In most case I never really care about seeing _Completed Tasks_ myself.

I have a similar approach in Excel, for me its quite handy to have the completed tasks in reach before archiving them.  Sometimes a old task is activated again or needs to be done again. Thats just what I experience.

This could be done like above:

```
(normal todo list here)
_______________________________________

Completed [this is acutally strike-strough in todotxt.net]
Write a summary @rob
Buy pineapples @rob
Pay bills @tom
Eat an apple @robjefferies
```

or ordered by person:

```
(normal todo list here)
_______________________________________
@robert
Write a summary @rob
Buy pineapples @rob

@thomas
Pay bills @tom

@robjefferies
Eat an apple 
```

Thank you

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
