### ISSUE TITLE
[Feature request] Grayed "creation date" on task list 

### ISSUE THREAD

**Issue by iTuiTu** [benrhughes/todotxt.net#428]
It's hard to start to read the task names due to the long intro with 'creation date' turned on. 'Priority' and 'creation date' took a lot of space, but 'date' also is messing with the readability of the task. If slightly grayed - it will give the eye option to fast-jump to the task name.

**Comment by benrhughes** [comment]
Thanks for the suggestion, but as stated in the readme, I am no longer taking feature requests for this app.
