### ISSUE TITLE
Can checksum be provided? I cant check the authenticity of the file downloaded here. thx

### ISSUE THREAD

**Issue by ccchan234** [benrhughes/todotxt.net#429]
hi,

it will be hard to have a digital signature for the .exe as it costs some money.

how about provide a checksum e.g. sha1/256 for the files?
(would be better if signed with PGP)

yes someone who hacked the server could change both the .exe and the checksum.txt

but it's better than nothing.

thanks

**Comment by benrhughes** [comment]
I don't really see the value that this would bring. If you're truly worried about the authenticity of the exe, you can pull the code down and build it.
