### ISSUE TITLE
done my task how to mark Completed Task

### ISSUE THREAD

**Issue by domaingood** [benrhughes/todotxt.net#431]
When I done my task how to mark Completed Task by 
Keyboard shortcuts:
O or Ctrl+O: open todo.txt file
D or Ctrl+D : for Completed Task

Please make Keyboard shortcuts for Completed Task

**Comment by jdckr** [comment]
Just hit x to toggle completion state. All keyboard shortcuts are listed in the readme btw.

**Comment by domaingood** [comment]
Thank you @jdckr
