### ISSUE TITLE
Add subtask functionality

### ISSUE THREAD

**Issue by team-community** [benrhughes/todotxt.net#437]
Hi all. Many tasks are very complex or time-consuming. It makes sense to add subtask functionality. The user can break the task into small tasks and solve them over time. In the end, he will solve the main problem. It would be very helpful. For example, for tasks like learning languages.

**Comment by benrhughes** [comment]
Hi,
I don’t believe the [todo.txt format spec](https://github.com/todotxt/todo.txt/blob/master/README.md) supports subtasks. Because this app is a implementation of that spec, it won’t support sub tasks, either.
