### ISSUE TITLE
Unable to access files for todotxt.net

### ISSUE THREAD

**Issue by R0xiedog** [benrhughes/todotxt.net#442]
I recently changed my computer and have upgraded to Windows 11. When installing todotxt.net, I now get the following error:

"An unexpected error occurred
System.UnauthorizedAccessException: Access to the path 'C:\Users\xxxxx\OneDrive\Desktop\todo.txt' is denied."

Note that xxxxx is a substitute for the actual folder name, which I am not sharing here. 

Any ideas on how to fix this error?

**Comment by fleapower** [comment]
I know this has been awhile.  Hopefully, you've fixed this by now.  This is a Windows security feature.  When it happens, you should be able to click on the alert and taken to a settings window to allow you to give the app approval to modify the todo.txt files.
