### ISSUE TITLE
future

### ISSUE THREAD

**Issue by ghost** [benrhughes/todotxt.net#444]

**Comment by benrhughes** [comment]
You've opened and closed this a few times. I'm not quite sure why?

**Comment by benrhughes** [comment]
Well, firstly, I don't know what your questions means. External support for what? 

Secondly, that doesn't explain why you keep closing and re-opening the ticket.

**Comment by benrhughes** [comment]
> Backup. Why isn't there syncing on Google Drive or Dropbox for my tasks with todotxt.net?
#
It's a text file. You can store it wherever you want, including Drive or Dropbox. There's no need for the app to support syncing itself.
