### ISSUE TITLE
User specified colours for context, project etc

### ISSUE THREAD

**Issue by benrhughes** [benrhughes/todotxt.net#68]

**Comment by Quicksi** [comment]
I think, priority colors aren't that important, as you can sort the list by priority.
Rather it would be nice to give the different parameters in todo.txt different colors
One color for all of the @context tags, another for all the +project tags, another for all due:'s, and so on

I like the way it's implemented in the top image on todotxt.com
![todotxt_colors](https://cloud.githubusercontent.com/assets/12952339/8232190/e1687e4a-15cd-11e5-91c5-1a4b939d2214.PNG)

In fact, i wouldn't use priority colors for the todo-item-text, but use the same color (grey, white, black) for all of them.
Priority color could be implemented by coloring the (A), (B), etc
I gimped a screenshot of todotxt.net to show what i mean:)
![todotxt_colors](https://cloud.githubusercontent.com/assets/12952339/8232802/adfc0978-15d2-11e5-9da9-ff6854e8aaf8.png)

What do you think?

**Comment by mjdescy** [comment]
@Quicksi. Yes, those are good ideas. I also think color contexts, projects, and due dates is more important than highlighting priorities. (Look at [my Mac app](https://mjdescy.github.io/TodoTxtMac/), for example.)

The main reason colors aren't used more in Todotxt.net (right now) is it is really hard to implement in WPF. .NET's handling for that kind of syntax highlighting is pretty much nonexistent, at least compared to how it can done in Cocoa/Mac OS X. I was never able to decide upon a solution. 

Also, WPF doesn't provide a proper color picker control, which complicates implementing user-selectable colors. I know there are some options out there, such as [Extended WPF Tookit](https://wpftoolkit.codeplex.com/wikipage?title=ColorPicker&referringTitle=Documentation). We could figure out how to implement something like that after we have found a solution to syntax highlighting.

I would love someone with WPF & XAML experience to suggest some methods or provide some code that implements syntax highlighting.

**Comment by benrhughes** [comment]
@Quicksi I agree with you and @kingsinger. Lets re-purpose this issue to that end. However @mjdescy is correct, in that WPF doesn't make this an easy thing to do, unfortunately.

**Comment by Quicksi** [comment]
@mjdescy Oh yeah, i love how your Mac app implements it.. perhaps i should by a MAC :D
joking aside: what do you mean in terms of nonexisting syntax highlighting?
Isn't it possible to use different colors in one single line or is it not possible to highlight special phrases (e.g. everythink starting with a "@")? in this case, perhaps some string operations could help?

According to the color picker, i would be happy with fixed colors in a first step :)

**Comment by mjdescy** [comment]
@Quicksi Honestly, you should buy a Mac. They are way better... :-)

WPF doesn't offer a simple way to programatically color parts of a plaintext string. You either have to convert it to rich text and color it that way (which is confusing) or you have to try something like splitting the string into a bunch of Run objects and formatting each Run depending on what kind of string it represents. I think the latter option would be the better one. It is just kind of a pain to implement.

**Comment by Quicksi** [comment]
@mjdescy ah ok, i understand
Well, i'm not used to C# (i'm in C/C++ embedded).
I don't know if i'm able to work on the code, but i'm going to have a look :)

**Comment by Quicksi** [comment]
Ok... i had a look and understand what you mean :/
Every ToDo-Item in the App is a ListBoxItem. It's possible to change Properties of the whole ListBoxItem (like Foreground)... but that's it.

Just brainstorming:
Could it be possible to put an object inside every ListBoxItem, that hold formatable text (if there exists such an object).
Or to dynamicaly cascade objects (e.g. labels) within each ListBoxItem? one object for each textelement (textelements split by <SPACE>). In order to change Foreground property for every single object accoring to the contained string (e.g. "Starts with @")

**Comment by bttrx** [comment]
+1

**Comment by se16n** [comment]
Hi all!

@mjdescy @benrhughes Guys is there any solution found?

Using this app a lot and it's really missing this feature...

**Comment by mjdescy** [comment]
> I haven't been looking into it for a long time, to be honest. I've been working on an iOS todo.txt app called SwiftoDo, because the official iOS client stopped working sometime last year.

For todotxt.net, the thing I thought might work is to subclass the text field classes, break up the task string into separate words, then generate runs (which can have different colors) for each word. I just haven't had the chance to work on it.

**Comment by se16n** [comment]
Hi Michael! I really fall in love with your mac implementation of todo.txt concept! So sad that todotxtnet seems like abandoned... 15.02.2016, 19:41, "Michael Descy" <notifications@github.com>:> I haven't been looking into it for a long time, to be honest. I've been working on an iOS todo.txt app called SwiftoDo, because the official iOS client stopped working sometime last year.  For todotxt.net, the thing I thought might work is to subclass the text field classes, break up the task string into separate words, then generate runs (which can have different colors) for each word. I just haven't had the chance to work on it.—Reply to this email directly or view it on GitHub.   -- Роман.

**Comment by benrhughes** [comment]
Not so much abandoned, it's more that I consider it feature complete, so I
don't have a lot of motivation to add features. Also,  over the lifetime of
the app, I've gone from having 2 kids to 4, so I don't have the same sort
if time, either :)

Essentially, for new features I'm relying on interested contributors (like
Mike).

**Comment by se16n** [comment]
@mjdescy Hi Michael! Hope you're doing well!

Don't you mind if i'll follow up you on this topic?

Seems like only you is the only person who can make it real.

**Comment by hellium** [comment]
I working on this, looks promising.

![image](https://user-images.githubusercontent.com/1141149/45134236-2ddebf80-b1e5-11e8-9e1d-4483e1b72292.png)

**Comment by jucor** [comment]
Binary released in https://github.com/jucor/todotxt.net/releases/tag/v3.3.1.1 for those wanting to use it. Thanks @hellium  for the actual work!
