### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by benrhughes** [benrhughes/todotxt.net#9]
Currently filtering is simple. Eg

@Work
Fix
-Build

Would include all tasks that contain "@Work" AND "Fix" AND NOT "Build".

It would be nice (though it would massively increase the complexity of the filtering code) if we use more complex expressions, for example:

@work AND (+fix OR +build)

**Comment by flusi100** [comment]
+1 from my side

**Comment by bttrx** [comment]
+1

**Comment by fmartelg** [comment]
+1 This is critical to my use case as a desktop companion to https://github.com/mpcjanssen/simpletask-android.git which does advance filtering (AND, OR, etc).

**Comment by symera** [comment]
+1

**Comment by symera** [comment]
+1

**Comment by medevac-** [comment]
@benrhughes I am a newbie but would like to work on this, can you point me in the right direction?
